### ISSUE TITLE
vue3-sample 실행하면 오류가 나느것 같아요

### ISSUE THREAD

**Issue by sjp7878** [realgrid/realgrid2-examples#11]
vue3-sample 실행하면 다음과 같은 오류가 나는것 같습니다.

 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'addChild' of undefined"

**Comment by onlydel** [comment]
해당 오류는 라이선스가 만료되어 발생하는 오류 같습니다.
샘플 코드에 포함된 라이선스는 임시 발급된 라이선스 입니다.
service.realgrid.com 에 가셔서 가입하시고 개발용 라이선스를 발급 받으신 다음 아래 코드 부분에 라이선스 키를 입력해 주시면 됩니다.

https://github.com/realgrid/realgrid2-examples/blob/0427b710011b136b75693f9481444f293848970f/vue3-sample/public/index.html#L10

**Comment by sjp7878** [comment]
> 해당 오류는 라이선스가 만료되어 발생하는 오류 같습니다.
> 샘플 코드에 포함된 라이선스는 임시 발급된 라이선스 입니다.
> 
> * [service.realgrid.com](http://service.realgrid.com/) 에 가셔서 가입하시고
> * [프로젝트 추가](http://service.realgrid.com/projects/new) 하시고
> * 개발용 라이선스를 발급 받으신 다음 아래 코드 부분에 라이선스 키를 입력해 주시면 됩니다.
> 
> https://github.com/realgrid/realgrid2-examples/blob/0427b710011b136b75693f9481444f293848970f/vue3-sample/public/index.html#L10

아 라이센스 문제였군요. 감사합니다.
